import { Injectable } from '@angular/core';
import { FormSchema } from '../models/form.model';

@Injectable({ providedIn: 'root' })
export class FormDataService {
  getFormSchema(): FormSchema {
    return {
      formName: 'Employee Registration Form',
      saveBtnLabel: 'Submit',
      resetBtnLabel: 'Reset',
      formControls: [
        {
          name: 'firstName',
          label: 'First Name',
          class: 'col-md-4',
          placeholder: 'Enter First Name',
          type: 'text',
          validators: { required: true, minLength: 2 },
        },
        {
          name: 'lastName',
          label: 'Last Name',
          class: 'col-md-4',
          placeholder: 'Enter Last Name',
          type: 'text',
          validators: { required: true },
        },
        {
          name: 'fatherHusbandName',
          label: 'Father/Husband Name',
          class: 'col-md-4',
          placeholder: 'Enter Name',
          type: 'text',
          validators: { required: true },
        },
        {
          name: 'dob',
          label: 'Date of Birth',
          class: 'col-md-4',
          placeholder: '',
          type: 'date',
          validators: { required: true },
        },
        {
          name: 'mobile',
          label: 'Mobile Number',
          class: 'col-md-4',
          placeholder: 'Enter Mobile',
          type: 'text',
          validators: { required: true, pattern: '^\\d{10}$' },
        },
        {
          name: 'email',
          label: 'Email',
          class: 'col-md-4',
          placeholder: 'Enter Email',
          type: 'email',
          validators: { required: true, email: true },
        },
        {
          name: 'aadhaar',
          label: 'Aadhaar Number',
          class: 'col-md-4',
          placeholder: 'Enter Aadhaar',
          type: 'text',
          validators: { required: true, pattern: '^\\d{12}$' },
        },
        {
          name: 'pan',
          label: 'PAN Number',
          class: 'col-md-4',
          placeholder: 'Enter PAN',
          type: 'text',
          validators: { required: true, pattern: '^[A-Z]{5}[0-9]{4}[A-Z]{1}$' },
        },
        {
          name: 'pfUan',
          label: 'PF UAN Number',
          class: 'col-md-4',
          placeholder: 'Enter PF UAN Number',
          type: 'text',
          validators: { required: true, pattern: '^[A-Z]{2}[A-Z0-9]{10}$' },
        },

        {
          name: 'gender',
          label: 'Gender',
          class: 'col-md-2',
          placeholder: '',
          type: 'radio',
          validators: { required: true },
          options: [
            { label: 'Male', value: 'male' },
            { label: 'Female', value: 'female' },
          ],
        },
        {
          name: 'maritalStatus',
          label: 'Marital Status',
          class: 'col-md-2',
          placeholder: '',
          type: 'radio',
          validators: { required: true },
          options: [
            { label: 'Married', value: 'married' },
            { label: 'Unmarried', value: 'unmarried' },
          ],
        },
        {
          name: 'department',
          label: 'Department',
          type: 'select',
          options: [
            { label: 'IT', value: 'IT' },
            { label: 'Finance', value: 'Finance' },
            { label: 'HR', value: 'HR' },
          ],
          placeholder: 'Select department',
          class: 'col-md-2',
          validators: { required: true },
        },
        {
          name: 'subDepartment',
          label: 'Sub Department',
          type: 'text',
          placeholder: 'Enter sub department',
          class: 'col-md-2',
          validators: {},
        },
        {
          name: 'designation',
          label: 'Designation',
          type: 'text',
          placeholder: 'Enter designation',
          class: 'col-md-2',
          validators: { required: true },
        },
        {
          name: 'role',
          label: 'Role',
          type: 'text',
          placeholder: 'Enter role',
          class: 'col-md-2',
          validators: { required: true },
        },
        {
          name: 'presentAddress',
          label: 'Present Address',
          type: 'textarea',
          placeholder: 'Enter present address',
          class: 'col-md-4',
          validators: { required: true },
        },
        {
          name: 'permanentAddress',
          label: 'Permanent Address',
          type: 'textarea',
          placeholder: 'Enter permanent address',
          class: 'col-md-4',
          validators: { required: true },
        },
        {
          name: 'state',
          label: 'State',
          type: 'text',
          placeholder: 'Enter state',
          class: 'col-md-4',
          validators: { required: true },
        },
        {
          name: 'city',
          label: 'City',
          type: 'text',
          placeholder: 'Enter city',
          class: 'col-md-4',
          validators: { required: true },
        },
        {
          name: 'district',
          label: 'District',
          type: 'text',
          placeholder: 'Enter district',
          class: 'col-md-4',
          validators: {},
        },
        {
          name: 'pincode',
          label: 'Pincode',
          type: 'text',
          placeholder: 'Enter pincode',
          class: 'col-md-4',
          validators: { required: true, pattern: '^[0-9]{6}$' },
        },
      ],
    };
  }
}
